# Generated by Django 5.2.7 on 2025-10-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='code_example',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='theory',
        ),
    ]
