# Generated by Django 5.2.7 on 2026-03-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
