# Generated by Django 5.2.7 on 2025-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_remove_documentation_code_example_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='collection_backgrounds/'),
        ),
    ]
