# Generated by Django 5.2.7 on 2025-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_project_technology_projectimage_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='technology_icons/'),
        ),
    ]
