# Generated by Django 5.2.7 on 2025-10-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_alter_technology_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
