# Generated by Django 5.2.7 on 2025-10-17 11:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_project_short_description_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed project description.'),
        ),
    ]
