# Generated by Django 5.2.7 on 2025-10-18 12:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Main documentation content with rich text editor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed project description.'),
        ),
    ]
