# Generated by Django 5.2.7 on 2025-10-18 18:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_alter_documentation_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Main documentation content with rich text editor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed project description.'),
        ),
    ]
