# Generated by Django 5.2.7 on 2025-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_alter_documentation_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI'), ('datascience', 'DataScience')], max_length=30, null=True),
        ),
    ]
